title:            Conquer By Fortitude
tagline:          conquerbyfortitude
description:      The blog of Padraic Doyle.
#Comment out url when working locally to resolve base urls correctly
#url: http://www.conquerbyfortitude.com

# Owner/author information
owner:
  name:           Padraic Doyle
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          padraic@padraicdoyle.com
  twitter:        padraicdoyle
  github:         padraicdoyle
  instagram:      padraicdoyle
  disqus:         conquerbyfortitude
  # Plug in your disqus shortname!


# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/padraicdoyle
    external: true
  - title: Projects
    url: /projects

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]